import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

// this is the font for the entire application
const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

// this is the metadata for the entire application
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

// this is the layout for the entire application
export default function RootLayout({ children, modal }: LayoutProps<'/'>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                {children}
                {modal}
            </body>
        </html>
    );
}
